import { PhotoCategory } from '@acceptance/shared';
import type { SnagDefinition } from './schema.js';

/**
 * Snag taxonomy for TE BIG-EDGE router installations (ASR-9902/9906, NCS-57C3).
 *
 * Sources: the three reviewer snag files (po17 sangs, po18 sangs, sangs afro & T.t),
 * the SID "Acceptance check list" (NASR3 R21C), and the approved site photos.
 * `reviewerPhrasesAr` keeps the reviewers' own wording verbatim so remarks can be
 * mapped to codes automatically (T1.1) and so the model learns their vocabulary.
 *
 * Rules for editing:
 * - Codes are permanent once reviewers start labelling. Rename = deprecate + add.
 * - Prefer a specific code; the *_UNTIDY codes are the fallback for the same family.
 * - Bump TAXONOMY_VERSION on every change (it is part of the cached prompt prefix).
 */
export const TAXONOMY_VERSION = '2026-10-03.1';

type Cat = PhotoCategory;
const ALL: Cat[] = [...PhotoCategory.options];
const FIBER: Cat[] = ['patch_cords', 'router', 'odf_cross_connect', 'odf_tie', 'test_room', 'uplink', 'rack'];
const ODF: Cat[] = ['odf_cross_connect', 'odf_tie', 'test_room', 'odf_cross_connect_labels', 'odf_tie_labels', 'rack'];
const RACK_INSIDE: Cat[] = ['rack', 'router', 'odf_cross_connect', 'odf_tie', 'pdu', 'power_system', 'management', 'patch_cords', 'test_room'];
const LABELLED: Cat[] = [
  'odf_cross_connect_labels', 'odf_tie_labels', 'uplink_labels', 'power_labels',
  'router', 'rack', 'odf_cross_connect', 'odf_tie', 'pdu', 'test_room', 'uplink', 'earth_path', 'management',
];
const PATHS: Cat[] = ['duct', 'patch_cords', 'armoured_cables', 'uplink', 'management', 'power_path', 'earth_path', 'power_system'];
const FLOOR: Cat[] = ['rack', 'rack_base', 'duct', 'armoured_cables', 'power_path', 'earth_path', 'management', 'uplink'];
const POWER: Cat[] = ['pdu', 'power_path', 'earth_path', 'power_labels', 'power_system'];

export const SNAG_TAXONOMY: readonly SnagDefinition[] = [
  // ───────────────────────────── photo quality (any category) ─────────────────────────────
  {
    code: 'PERSON_IN_FRAME',
    group: 'photo_quality',
    origin: 'snag_docs',
    titleEn: 'Person visible in photo',
    titleAr: 'ظهور شخص في الصورة',
    descriptionEn:
      'A person (body, face, legs, clothing) appears in a final acceptance photo. A hand or fingers holding a label flat for a label close-up is NOT this snag.',
    descriptionAr: 'ظهور شخص (جسم أو وش أو رجلين أو هدوم) في صورة التسليم النهائية. إيد ماسكة الليبول عشان يتقري في صور الليبولات مش سناج.',
    defaultSeverity: 'major',
    categories: ALL,
    visualCues: [
      'human body, head, face, legs or clothing anywhere in the frame, including reflections in rack doors or ODF windows',
      'a person working in the background of a rack or room overview shot',
    ],
    confusableWith: [],
    reviewerPhrasesAr: ['نصور بدون ظهور الشخص', 'عدم ظهور شخص في الصور النهائيه', 'عدم ظهور شخص في الصوره'],
    qualityIssue: 'person_in_frame',
    fixInstructionAr: 'نعيد التصوير من غير ما حد يظهر في الكادر، ونبعد أي حد واقف ورا الراك.',
    fixInstructionEn: 'Retake the photo with nobody in the frame; ask anyone behind the rack to step away.',
  },
  {
    code: 'PHOTO_BLURRY',
    group: 'photo_quality',
    origin: 'photo_quality',
    titleEn: 'Photo blurry / out of focus',
    titleAr: 'الصورة مهزوزة أو مش واضحة',
    descriptionEn: 'Motion blur or out-of-focus image so that the items the category must show (labels, cords, bolts) cannot be judged.',
    descriptionAr: 'الصورة مهزوزة أو الفوكس مش مظبوط لدرجة إن الحاجات المطلوبة (الليبولات، البشات، المسامير) مش باينة.',
    defaultSeverity: 'major',
    categories: ALL,
    visualCues: ['smeared edges, double contours', 'label text that cannot be read in a label close-up', 'video screenshot with play button overlay'],
    confusableWith: ['PHOTO_TOO_DARK'],
    reviewerPhrasesAr: [],
    qualityIssue: 'blurry',
    fixInstructionAr: 'نثبت الموبايل ونستنى الفوكس ونعيد التصوير، ومنبعتش سكرين شوت من فيديو.',
    fixInstructionEn: 'Hold the phone steady, wait for focus and retake; do not send video screenshots.',
  },
  {
    code: 'PHOTO_TOO_DARK',
    group: 'photo_quality',
    origin: 'photo_quality',
    titleEn: 'Photo too dark / poor lighting',
    titleAr: 'الصورة ضلمة',
    descriptionEn: 'Under-exposed photo (typical inside racks and under raised floor) where the subject cannot be assessed.',
    descriptionAr: 'الصورة ضلمة (بتحصل جوه الراك وتحت البلاط) ومش باين فيها اللي محتاجين نشوفه.',
    defaultSeverity: 'major',
    categories: ALL,
    visualCues: ['most of the frame near-black', 'subject only visible as silhouettes', 'strong backlight hiding the subject'],
    confusableWith: ['PHOTO_BLURRY'],
    reviewerPhrasesAr: [],
    qualityIssue: 'dark',
    fixInstructionAr: 'نستخدم الفلاش أو كشاف ونعيد التصوير.',
    fixInstructionEn: 'Use the flash or a torch and retake.',
  },
  {
    code: 'WRONG_CATEGORY',
    group: 'photo_quality',
    origin: 'photo_quality',
    titleEn: 'Photo does not match its category',
    titleAr: 'الصورة مش تبع البند ده',
    descriptionEn: 'The photo shows a different subject than the category it was uploaded under (e.g. a PDU photo uploaded as rack_base).',
    descriptionAr: 'الصورة متصورة لحاجة غير البند اللي اترفعت عليه (مثلاً صورة PDU مترفوعة على قاعدة الراك).',
    defaultSeverity: 'major',
    categories: ALL,
    visualCues: ['main subject belongs to another category', 'no element required by this category is visible'],
    confusableWith: ['SUBJECT_NOT_FULLY_VISIBLE'],
    reviewerPhrasesAr: [],
    qualityIssue: 'wrong_subject',
    fixInstructionAr: 'نرفع الصورة على البند الصح أو نصور البند المطلوب.',
    fixInstructionEn: 'Move the photo to the correct category or take the required shot.',
  },
  {
    code: 'SUBJECT_NOT_FULLY_VISIBLE',
    group: 'photo_quality',
    origin: 'photo_quality',
    titleEn: 'Subject cropped or obstructed',
    titleAr: 'البند مش ظاهر كله في الصورة',
    descriptionEn:
      'Right category, but part of what must be shown is cut off or hidden (e.g. half the rack base, label folded, ODF door hiding ports).',
    descriptionAr: 'الصورة للبند الصح بس جزء مهم مقصوص أو مستخبي (نص القاعدة، ليبول مطبق، باب الاو دي اف مداري البورتات).',
    defaultSeverity: 'minor',
    categories: ALL,
    visualCues: ['required element cut by the frame edge', 'object or door blocking the subject', 'label turned so its text is not facing the camera'],
    confusableWith: ['WRONG_CATEGORY', 'PHOTO_BLURRY'],
    reviewerPhrasesAr: [],
    fixInstructionAr: 'نرجع لورا شوية أو نغير الزاوية ونصور البند كامل.',
    fixInstructionEn: 'Step back or change the angle so the whole subject is in frame.',
  },

  // ───────────────────────────── housekeeping ─────────────────────────────
  {
    code: 'SPARE_LEFT_IN_ODF',
    group: 'housekeeping',
    origin: 'snag_docs',
    titleEn: 'Spare cords/items left inside ODF',
    titleAr: 'الاسبير متساب جوه الاو دي اف',
    descriptionEn:
      'Spare patch cords, pigtails, adapters or cord coils are stored inside the ODF tray/window. Spares must be bagged and stored away, not in the ODF.',
    descriptionAr: 'باتشات أو بيج تيل أو كابلرات اسبير متشالة جوه الاو دي اف أو باينة من الشباك بتاعه. الاسبير يتحط في كيس ويتشال بعيد عن الاو دي اف.',
    defaultSeverity: 'major',
    categories: ODF,
    visualCues: [
      'loose coils of yellow patch cord lying inside the ODF behind the transparent window',
      'unconnected connectors or SC/LC adapters resting at the bottom of the ODF tray',
      'cords inside the ODF that do not terminate on a port',
    ],
    confusableWith: ['SPARE_LEFT_IN_RACK', 'PATCH_CORD_EXCESS_LENGTH'],
    reviewerPhrasesAr: [
      'نشيل الاسيبر  من جوا الاو دي اف',
      'نشيل الاسيبر من جواه ال او دي اف',
      'الاسيبر جوا الاو دي اف',
      'الاسبير داخل الاو دي اف',
      'الاسيبر يتشل من او دي اف',
      'نشيل الاسيبر من الاو دي اف',
      'عدم وضع الاسيبر داخل الاو دي اف',
      'نحط الاسيبر في كيس مش جواه الاو دي اف',
    ],
    fixInstructionAr: 'نشيل الاسبير من جوه الاو دي اف ونحطه في كيس ونخفيه بعيد عن الراك.',
    fixInstructionEn: 'Remove all spares from the ODF, put them in a bag and store them out of sight.',
  },
  {
    code: 'SPARE_LEFT_IN_RACK',
    group: 'housekeeping',
    origin: 'snag_docs',
    titleEn: 'Spare items left in rack / in front of router',
    titleAr: 'الاسبير متساب في الراك أو قدام الراوتر',
    descriptionEn:
      'Spare material (cords, SFPs, cards, accessories) left on the rack floor, on top of equipment or in front of the router. Not for items inside an ODF (use SPARE_LEFT_IN_ODF) or packaging (use PACKAGING_OR_DEBRIS_LEFT).',
    descriptionAr: 'حاجات اسبير (باتشات، SFP، كروت، اكسسوارات) متسابة في أرضية الراك أو فوق الأجهزة أو قدام الراوتر. لو جوه الاو دي اف يبقى SPARE_LEFT_IN_ODF ولو كرتون يبقى PACKAGING_OR_DEBRIS_LEFT.',
    defaultSeverity: 'major',
    categories: RACK_INSIDE,
    visualCues: [
      'bags, boxes of SFPs or loose cord coils on the rack floor or shelf',
      'spare items placed in front of the router chassis',
      'accessory kits left on top of equipment',
    ],
    confusableWith: ['SPARE_LEFT_IN_ODF', 'PACKAGING_OR_DEBRIS_LEFT'],
    reviewerPhrasesAr: [
      'نشيل الاسيبر بتاع الرواتر',
      'عدم وضع الاسيبر في الاتجاه الامامي من الرواتر',
      'الاسيبر نحطه في كيس ونخفي',
      'نشيل لاسيبر',
    ],
    fixInstructionAr: 'نشيل الاسبير من الراك ونحطه في كيس ونخزنه بعيد، ومفيش حاجة تتساب قدام الراوتر.',
    fixInstructionEn: 'Remove spares from the rack, bag them and store them away; nothing may stay in front of the router.',
  },
  {
    code: 'PACKAGING_OR_DEBRIS_LEFT',
    group: 'housekeeping',
    origin: 'snag_docs',
    titleEn: 'Cardboard, packaging or debris left',
    titleAr: 'كرتون أو مخلفات متسابة',
    descriptionEn: 'Cardboard boxes, plastic wrap, cable-tie off-cuts, tools or installation waste left in the rack, under the floor or around the site.',
    descriptionAr: 'كراتين أو نايلون أو بواقي رباطات أو عدة أو مخلفات تركيب متسابة في الراك أو تحت البلاط أو في الموقع.',
    defaultSeverity: 'major',
    categories: ALL,
    visualCues: ['brown cardboard box inside a rack', 'plastic bags / wrapping', 'cut cable-tie tails or offcuts on the floor', 'tools left behind'],
    confusableWith: ['SPARE_LEFT_IN_RACK', 'DUST_OR_DIRT'],
    reviewerPhrasesAr: ['نشيل الكرتونه من جواه الراك'],
    fixInstructionAr: 'نشيل الكرتون وأي مخلفات من الراك والموقع وننضف المكان.',
    fixInstructionEn: 'Remove all cardboard, packaging and waste from the rack and site.',
  },
  {
    code: 'DUST_OR_DIRT',
    group: 'housekeeping',
    origin: 'snag_docs',
    titleEn: 'Dust or dirt on rack / ODF / equipment',
    titleAr: 'تراب على الراك أو الاو دي اف',
    descriptionEn: 'Visible dust, cement powder or dirt on the rack floor, equipment tops, ODF or trays after installation.',
    descriptionAr: 'تراب أو بودرة أسمنت أو وساخة باينة على أرضية الراك أو فوق الأجهزة أو على الاو دي اف أو التراي بعد التركيب.',
    defaultSeverity: 'minor',
    categories: ALL,
    visualCues: ['grey dust layer on black rack surfaces', 'footprints or powder on rack floor', 'dust on ODF window or router top'],
    confusableWith: ['MARKER_OR_STAIN_MARKS', 'PACKAGING_OR_DEBRIS_LEFT'],
    reviewerPhrasesAr: ['نسمح التراب من جواه الراك', 'نمسح او دي اف', 'مسح ااراك و او دي اف', 'نمسح الراك من التراب', 'نمسح التراب', 'نسمح التراب', 'نمسح الراك'],
    fixInstructionAr: 'نمسح الراك والاو دي اف والأجهزة من التراب ونعيد التصوير.',
    fixInstructionEn: 'Clean the rack, ODF and equipment, then retake.',
  },
  {
    code: 'MARKER_OR_STAIN_MARKS',
    group: 'housekeeping',
    origin: 'snag_docs',
    titleEn: 'Marker writing / stains on surfaces ("الباغه")',
    titleAr: 'باغة (شخبطة ماركر أو بقع) على الأسطح',
    descriptionEn:
      'Marker or pen writing, smudges or stains left on equipment, ODF windows, rack panels or ducts. Writing on floor tiles is out of scope unless in the photo subject.',
    descriptionAr: 'كتابة ماركر أو قلم أو بقع أو شخبطة متسابة على الأجهزة أو شباك الاو دي اف أو جسم الراك أو الداكت.',
    defaultSeverity: 'minor',
    categories: ALL,
    visualCues: ['hand-written marker text or scribbles on ODF window, duct or rack', 'smudges / stains on transparent covers', 'leftover marking used during installation'],
    confusableWith: ['DUST_OR_DIRT'],
    reviewerPhrasesAr: ['نمسح الباغه', 'مسح الباغه', 'نسمح الباغه'],
    fixInstructionAr: 'نمسح الباغة (الماركر والبقع) بكحول أو منظف مناسب.',
    fixInstructionEn: 'Wipe off marker marks and stains with alcohol or a suitable cleaner.',
  },
  {
    code: 'RACK_DOOR_NOT_CLOSED',
    group: 'housekeeping',
    origin: 'snag_docs',
    titleEn: 'Rack door left open / not latched',
    titleAr: 'باب الراك مفتوح أو مش مقفول صح',
    descriptionEn:
      'A rack door (front, rear or side) that is not the one opened for the shot is left open or not latched properly. Doors deliberately opened to photograph the inside are acceptable.',
    descriptionAr: 'باب من أبواب الراك (قدام أو ورا أو جنب) غير الباب اللي اتفتح عشان التصوير متساب مفتوح أو مش مقفول صح.',
    defaultSeverity: 'minor',
    categories: ['rack', 'pdu', 'router', 'odf_cross_connect', 'odf_tie'],
    visualCues: ['rear door visibly open behind the open front', 'door ajar / misaligned, latch not engaged', 'closed-rack overview with a door standing open'],
    confusableWith: [],
    reviewerPhrasesAr: ['نقف الباب الخلفي', 'نقفل الباب', 'الباب مش مقفول بشكل صحيح', 'الباب مفتوح'],
    fixInstructionAr: 'نقفل كل أبواب الراك صح ونتأكد إن الكالون قافل.',
    fixInstructionEn: 'Close and latch all rack doors properly.',
  },

  // ───────────────────────────── fiber / patch cords ─────────────────────────────
  {
    code: 'PATCH_CORD_NOT_BUNDLED',
    group: 'fiber',
    origin: 'snag_docs',
    titleEn: 'Patch cords not bundled with velcro (اسكوتش)',
    titleAr: 'البشات مش متجمعة باسكوتش',
    descriptionEn:
      'Patch cords run loose or in several small groups instead of one bundle held by velcro (اسكوتش) at regular spacing (~15 cm per PIC, ~25 cm per MIC per SID).',
    descriptionAr: 'البشات سايبة أو متقسمة مجموعات بدل ما تكون حزمة واحدة متربطة باسكوتش على مسافات ثابتة (حوالي 15 سم للـ PIC و25 سم للـ MIC).',
    defaultSeverity: 'major',
    categories: FIBER,
    visualCues: [
      'long runs of yellow cords with no black velcro straps',
      'velcro straps very far apart or irregular',
      'several separate small bundles where one bundle is expected',
    ],
    confusableWith: ['PATCH_CORD_ROUTING_UNTIDY'],
    reviewerPhrasesAr: [
      'نحط الاسكوتش',
      '-نحط الاسكوتش',
      'نحط اسكوتش',
      'تجميع البشات في اسكوتش واحد',
      'نحط اسكوتش في البشتات لتظبط السستمه',
      'نحط اسكوتش لتظبيط شكل السستمه',
      'نضع اسكوتش في السستمه',
      'نحط اسكوتش نظبط السستمه باسكوتش',
      'وضع اسكوتش للتظبيط السستمه',
    ],
    fixInstructionAr: 'نجمع البشات في حزمة واحدة ونربطها اسكوتش على مسافات متساوية (15 سم تقريباً).',
    fixInstructionEn: 'Gather the cords into one bundle and strap with velcro at equal spacing (~15 cm).',
  },
  {
    code: 'PATCH_CORD_MULTIPLE_PATHS',
    group: 'fiber',
    origin: 'snag_docs',
    titleEn: 'Patch cords not taking a single path',
    titleAr: 'مسار البشات مش من مكان واحد',
    descriptionEn: 'Cords of the same device/ODF leave or enter through more than one route (both sides, through the middle) instead of one defined path.',
    descriptionAr: 'بشات نفس الجهاز أو الاو دي اف طالعة أو داخلة من أكتر من مكان (من الجنبين أو من النص) بدل مسار واحد.',
    defaultSeverity: 'major',
    categories: FIBER,
    visualCues: ['cords exiting ODF/router on both left and right sides', 'some cords dropping through the middle of the rack', 'cords entering the basket tray at several points'],
    confusableWith: ['PATCH_CORD_ROUTING_UNTIDY', 'PATCH_CORD_CROSSING'],
    reviewerPhrasesAr: ['مسار البشات من مكان واحد', 'تعديل مسار الباتشات', 'تتعديل مسار الباتشات'],
    fixInstructionAr: 'نعدل المسار بحيث كل البشات تطلع من جنب واحد وتمشي في مسار واحد لحد التراي.',
    fixInstructionEn: 'Re-route so all cords leave on one side and follow a single path to the tray.',
  },
  {
    code: 'PATCH_CORD_EXCESS_LENGTH',
    group: 'fiber',
    origin: 'snag_docs',
    titleEn: 'Excess patch cord length / slack loops',
    titleAr: 'أطوال زيادة في البشات',
    descriptionEn: 'Visible slack loops or hanging excess length on patch cords instead of being organised on the ladder/tray or cable organisers.',
    descriptionAr: 'لفات أو أطوال زيادة في البشات مدلدلة أو باينة بدل ما تتنظم على السلم أو التراي أو المنظمات.',
    defaultSeverity: 'major',
    categories: FIBER,
    visualCues: ['loops of cord hanging below the bundle', 'cords bulging out of the vertical organiser', 'coiled extra length near router or ODF'],
    confusableWith: ['SPARE_LEFT_IN_ODF', 'PATCH_CORD_ROUTING_UNTIDY'],
    reviewerPhrasesAr: ['اطوال البشتات زياده', 'في اطوال زياده في الباتشات'],
    fixInstructionAr: 'نلم الأطوال الزيادة وننظمها على السلم أو المنظم أو نستخدم باتش بطول مناسب.',
    fixInstructionEn: 'Take up the slack on the tray/organiser or replace with a correct-length cord.',
  },
  {
    code: 'PATCH_CORD_CROSSING',
    group: 'fiber',
    origin: 'snag_docs',
    titleEn: 'Patch cords crossing each other',
    titleAr: 'كروس في البشات',
    descriptionEn: 'Cords or bundles cross over each other instead of running in parallel ordered layers.',
    descriptionAr: 'البشات أو الحزم معدية فوق بعض (كروس) بدل ما تمشي جنب بعض بالترتيب.',
    defaultSeverity: 'major',
    categories: FIBER,
    visualCues: ['X-shaped crossings of cords or bundles', 'one bundle passing over another at a tray entry', 'cords weaving between organiser fingers'],
    confusableWith: ['PATCH_CORD_ROUTING_UNTIDY', 'PATCH_CORD_MULTIPLE_PATHS'],
    reviewerPhrasesAr: ['في كروس في الباتشات وسستمه غير صحيحه'],
    fixInstructionAr: 'نفك الكروس ونرتب البشات بالترتيب على حسب البورتات.',
    fixInstructionEn: 'Undo the crossings and re-lay cords in port order.',
  },
  {
    code: 'PATCH_CORD_UNDER_TENSION',
    group: 'fiber',
    origin: 'snag_docs',
    titleEn: 'Patch cords pulled tight (no slack)',
    titleAr: 'البشات مشدودة',
    descriptionEn: 'Cords are stretched taut between connector and organiser/tray, pulling on the connectors.',
    descriptionAr: 'البشات مشدودة على الآخر بين الكونكتور والمنظم أو التراي وبتشد على الكونكتورات.',
    defaultSeverity: 'major',
    categories: FIBER,
    visualCues: ['straight taut cords with no relief near connectors', 'connectors angled / pulled out of line', 'cords pressed hard against sharp edges'],
    confusableWith: ['FIBER_BEND_RADIUS_TOO_TIGHT'],
    reviewerPhrasesAr: ['البشات مشدوده'],
    fixInstructionAr: 'نرخي البشات ونسيب طول مناسب قبل الكونكتور من غير ما يبقى فيه أطوال زيادة.',
    fixInstructionEn: 'Relieve the tension with a small service slack near connectors (without creating excess loops).',
  },
  {
    code: 'FIBER_BEND_RADIUS_TOO_TIGHT',
    group: 'fiber',
    origin: 'snag_docs',
    titleEn: 'Fiber bend radius too tight',
    titleAr: 'الكرفة (ثنية) البشات ضيقة',
    descriptionEn: 'Cords or armoured fibre bent sharply (at tray drops, rack entries, organiser edges) instead of following a wide curve or waterfall guide.',
    descriptionAr: 'البشات أو الارمود متثنية ثنية حادة (عند النزلة من التراي أو دخول الراك أو حرف المنظم) بدل كرفة واسعة أو على الووترفول.',
    defaultSeverity: 'major',
    categories: [...FIBER, 'armoured_cables'],
    visualCues: ['sharp kink where the bundle drops from the tray into the rack', 'cords bent around a metal edge', 'bundle not following the waterfall guide'],
    confusableWith: ['PATCH_CORD_UNDER_TENSION'],
    reviewerPhrasesAr: ['توسيع الكرف بتاع بتاع الباتشات'],
    fixInstructionAr: 'نوسع الكرفة ونمشي البشات على الووترفول أو المنظم من غير ثني حاد.',
    fixInstructionEn: 'Widen the bend and route over the waterfall/organiser without sharp kinks.',
  },
  {
    code: 'PATCH_CORD_ROUTING_UNTIDY',
    group: 'fiber',
    origin: 'snag_docs',
    titleEn: 'Patch cord dressing untidy (السستمه) — fallback',
    titleAr: 'سستمة البشات مش مظبوطة',
    descriptionEn:
      'General patch cord dressing ("السستمه") is not neat and none of the more specific fiber codes fits. Prefer NOT_BUNDLED, MULTIPLE_PATHS, EXCESS_LENGTH, CROSSING, UNDER_TENSION or BEND_RADIUS when they apply.',
    descriptionAr: 'سستمة البشات عموماً مش مظبوطة ومفيش كود أدق ينطبق. لو فيه سبب واضح (اسكوتش، مسار، أطوال، كروس، شد، كرفة) نستخدم الكود بتاعه.',
    defaultSeverity: 'major',
    categories: FIBER,
    visualCues: ['messy, uneven cord layout', 'cords not following organiser fingers', 'bundle shape irregular / bulging'],
    confusableWith: [
      'PATCH_CORD_NOT_BUNDLED',
      'PATCH_CORD_MULTIPLE_PATHS',
      'PATCH_CORD_EXCESS_LENGTH',
      'PATCH_CORD_CROSSING',
      'PATCH_CORD_UNDER_TENSION',
      'FIBER_BEND_RADIUS_TOO_TIGHT',
    ],
    reviewerPhrasesAr: [
      'السستمه تتعدل',
      'نظبط السستمه',
      'نظبط شكل السستمه',
      'نعدل السستمه',
      'تتعدل السستمه',
      'تظبط السستمه',
      'سستمه الباتشات مش مظبوطه',
      'نخلي الستمه في مسارها المظبوط',
      'نظبط البشتات',
    ],
    fixInstructionAr: 'نعيد سستمة البشات: نرتبها ونمشيها في المنظمات ونربطها اسكوتش بشكل منتظم.',
    fixInstructionEn: 'Re-dress the cords neatly through the organisers and strap them evenly.',
  },
  {
    code: 'DUST_CAP_MISSING',
    group: 'fiber',
    origin: 'snag_docs',
    titleEn: 'Dust cap missing on unused coupler/port',
    titleAr: 'الكابلر من غير غطاء',
    descriptionEn: 'Unused ODF couplers (adapters) or unused router optical ports are left open without their protective dust cap.',
    descriptionAr: 'الكابلرات (الادابتر) الفاضية في الاو دي اف أو البورتات الفاضية في الراوتر من غير الغطاء بتاعها.',
    defaultSeverity: 'major',
    categories: ['odf_cross_connect', 'odf_tie', 'test_room', 'router', 'odf_cross_connect_labels', 'odf_tie_labels', 'uplink'],
    visualCues: [
      'empty green/blue SC adapter showing an open hole instead of a capped front',
      'one open adapter in an otherwise capped row',
      'open SFP cage or optical port without plug on the router',
    ],
    confusableWith: [],
    reviewerPhrasesAr: ['نغطي الكابلر', 'نغطي لكابلر', 'الكابلر مش راكب الغطاء بتاعه', 'الكابلر بدون غطاء', 'اغطاء الكابلر', 'غطاء الكابلر'],
    fixInstructionAr: 'نركب غطا على كل كابلر أو بورت فاضي.',
    fixInstructionEn: 'Fit a dust cap on every unused coupler and port.',
  },

  // ───────────────────────────── duct / tray / ladder ─────────────────────────────
  {
    code: 'DUCT_COVER_OPEN',
    group: 'duct_tray',
    origin: 'snag_docs',
    titleEn: 'Duct cover open / not closed at drop',
    titleAr: 'الداكت مفتوح (مش مقفول من النزلة)',
    descriptionEn: 'The duct exists but its cover is missing or not closed, typically at the drop (النزله) into the rack.',
    descriptionAr: 'الداكت موجود بس الغطا بتاعه مش مركب أو مش مقفول، غالباً عند النزلة على الراك.',
    defaultSeverity: 'major',
    categories: PATHS,
    visualCues: ['open-top duct with visible cords inside', 'cover lifted / displaced at the rack drop', 'gap between duct cover sections'],
    confusableWith: ['DUCT_SECTION_MISSING', 'DUCT_BROKEN'],
    reviewerPhrasesAr: ['نقفل الداكت من النزله', 'غلق الداكت بشكل صحيح'],
    fixInstructionAr: 'نقفل غطا الداكت كله خصوصاً عند النزلة على الراك.',
    fixInstructionEn: 'Close the duct cover along its full length, especially at the rack drop.',
  },
  {
    code: 'DUCT_SECTION_MISSING',
    group: 'duct_tray',
    origin: 'snag_docs',
    titleEn: 'Duct missing on part of the route',
    titleAr: 'الداكت مش مكمل في المسار',
    descriptionEn: 'Part of the cable route (often the drops / النزلات) has no duct at all, so cables run exposed.',
    descriptionAr: 'جزء من المسار (غالباً النزلات) مفيهوش داكت أصلاً والكابلات ماشية مكشوفة.',
    defaultSeverity: 'major',
    categories: PATHS,
    visualCues: ['cords running bare between two duct ends', 'vertical drop to rack without duct', 'duct ends abruptly before the rack'],
    confusableWith: ['DUCT_COVER_OPEN'],
    reviewerPhrasesAr: ['نكمل الداكت في النزلات', 'نحط داكت في باقي المسار'],
    fixInstructionAr: 'نكمل الداكت في باقي المسار والنزلات لحد دخول الراك.',
    fixInstructionEn: 'Install duct over the remaining route and drops up to the rack entry.',
  },
  {
    code: 'DUCT_TILTED',
    group: 'duct_tray',
    origin: 'snag_docs',
    titleEn: 'Duct tilted / not straight',
    titleAr: 'ميل في الداكت',
    descriptionEn: 'Duct run is tilted, sagging or not aligned with the tray/ladder.',
    descriptionAr: 'الداكت مايل أو مهبط أو مش على استقامة التراي أو السلم.',
    defaultSeverity: 'minor',
    categories: PATHS,
    visualCues: ['duct visibly sloping relative to the ladder', 'duct sections at different heights', 'duct twisted on its support'],
    confusableWith: ['CABLE_TRAY_MISALIGNED', 'DUCT_BROKEN'],
    reviewerPhrasesAr: ['ميل في الداكت'],
    fixInstructionAr: 'نعدل الداكت ونثبته على استقامة التراي.',
    fixInstructionEn: 'Straighten and re-fix the duct in line with the tray.',
  },
  {
    code: 'DUCT_BROKEN',
    group: 'duct_tray',
    origin: 'snag_docs',
    titleEn: 'Duct broken / damaged',
    titleAr: 'الداكت مكسور',
    descriptionEn: 'A duct section, cover or fitting is cracked, broken or deformed.',
    descriptionAr: 'جزء من الداكت أو الغطا أو الاكسسوار مشروخ أو مكسور أو مبعوج.',
    defaultSeverity: 'major',
    categories: PATHS,
    visualCues: ['cracks or missing pieces in white plastic duct', 'broken cover edge', 'deformed bend fitting'],
    confusableWith: ['DUCT_COVER_OPEN', 'DUCT_TILTED'],
    reviewerPhrasesAr: ['الداكت في جزء منه مكسور'],
    fixInstructionAr: 'نغير الجزء المكسور من الداكت.',
    fixInstructionEn: 'Replace the broken duct section.',
  },
  {
    code: 'RUBBER_GLAND_MISSING',
    group: 'duct_tray',
    origin: 'snag_docs',
    titleEn: 'Rubber gland / edge protector missing at opening',
    titleAr: 'رابر جلاد مش متركب',
    descriptionEn: 'Cables pass through a cut opening in a duct, tray or rack top without a rubber gland/grommet protecting them from the sharp edge.',
    descriptionAr: 'الكابلات معدية من فتحة مقصوصة في الداكت أو التراي أو سقف الراك من غير رابر جلاد يحميها من الحرف.',
    defaultSeverity: 'major',
    categories: [...PATHS, 'rack'],
    visualCues: ['cords exiting a duct through a bare cut hole', 'raw cut edge touching cables', 'rack-top cable entry without brush/grommet'],
    confusableWith: ['WALL_OPENING_NOT_SEALED'],
    reviewerPhrasesAr: ['نركب رابر جلاد'],
    fixInstructionAr: 'نركب رابر جلاد على الفتحة اللي الكابلات معدية منها.',
    fixInstructionEn: 'Fit a rubber gland/grommet on the opening the cables pass through.',
  },
  {
    code: 'CABLE_TRAY_MISALIGNED',
    group: 'duct_tray',
    origin: 'snag_docs',
    titleEn: 'Cable tray / ladder not level or misaligned',
    titleAr: 'الباسكت تراي أو السلم مش على نفس المستوى',
    descriptionEn: 'Basket tray, ladder rungs or sections are not at the same level, misaligned or not straight.',
    descriptionAr: 'الباسكت تراي أو درجات السلم أو أجزاءه مش على نفس المستوى أو مش على استقامة واحدة.',
    defaultSeverity: 'minor',
    categories: [...PATHS, 'rack_base'],
    visualCues: ['ladder rungs at different heights or angles', 'tray sections stepped at a joint', 'tray sloping where it should be level'],
    confusableWith: ['DUCT_TILTED', 'CABLE_TRAY_SUPPORT_MISSING'],
    reviewerPhrasesAr: ['الباكست تري مش نفس المستوي'],
    fixInstructionAr: 'نظبط الباسكت تراي والسلم على نفس المستوى ونربط الوصلات كويس.',
    fixInstructionEn: 'Level and align the tray/ladder sections and tighten the joints.',
  },
  {
    code: 'CABLE_TRAY_SUPPORT_MISSING',
    group: 'duct_tray',
    origin: 'snag_docs',
    titleEn: 'Tray support / hanger missing (دعامة)',
    titleAr: 'دعامة التراي مش متركبة',
    descriptionEn: 'A tray or ladder span lacks a support/hanger rod (دعامة / "دماعه") from ceiling or wall, leaving it unsupported.',
    descriptionAr: 'جزء من التراي أو السلم من غير دعامة (تعليقة من السقف أو الحيطة) وفاضل سايب.',
    defaultSeverity: 'major',
    categories: PATHS,
    visualCues: ['long unsupported tray span', 'tray end resting without hanger', 'ceiling above tray with no threaded rod where neighbours have one'],
    confusableWith: ['CABLE_TRAY_MISALIGNED'],
    reviewerPhrasesAr: ['تركيب دماعه'],
    fixInstructionAr: 'نركب دعامة (تعليقة) للتراي من السقف أو الحيطة.',
    fixInstructionEn: 'Install a support/hanger rod for the tray span.',
  },

  // ───────────────────────────── floor / rack / base ─────────────────────────────
  {
    code: 'FLOOR_OPENING_NOT_SEALED',
    group: 'floor_rack',
    origin: 'snag_docs',
    titleEn: 'Raised-floor opening not closed',
    titleAr: 'فتحة البلاط مش مقفولة',
    descriptionEn: 'A cut or removed raised-floor tile next to/around the rack leaves an open hole into the under-floor void.',
    descriptionAr: 'بلاطة مقصوصة أو مشالة جنب الراك أو حواليه وسايبة فتحة على تحت البلاط.',
    defaultSeverity: 'major',
    categories: FLOOR,
    visualCues: ['dark gap/hole in the floor next to the rack', 'missing tile or partially cut tile', 'cables visible under the floor through an opening'],
    confusableWith: ['RACK_FLOOR_GAP', 'WALL_OPENING_NOT_SEALED'],
    reviewerPhrasesAr: ['سد مكان البلاط', 'نقفل جزء البلاط للاخر'],
    fixInstructionAr: 'نقفل فتحة البلاط للآخر ببلاطة مقصوصة على المقاس أو غطا مناسب.',
    fixInstructionEn: 'Close the floor opening completely with a tile cut to size or a proper cover.',
  },
  {
    code: 'RACK_FLOOR_GAP',
    group: 'floor_rack',
    origin: 'snag_docs',
    titleEn: 'Gap between rack and floor tiles',
    titleAr: 'مسافة بين الراك والبلاط',
    descriptionEn: 'Visible gap between the bottom of the rack (plinth) and the surrounding floor tiles along the rack front/side.',
    descriptionAr: 'فيه مسافة باينة بين قاعدة الراك والبلاط اللي حواليه من قدام أو من الجنب.',
    defaultSeverity: 'major',
    categories: ['rack', 'rack_base'],
    visualCues: ['dark strip between rack plinth and tiles', 'rack bottom raised above tile level', 'tile edge not reaching the rack'],
    confusableWith: ['FLOOR_OPENING_NOT_SEALED'],
    reviewerPhrasesAr: ['عدم ترك مسافه بين الراك والبلاط'],
    fixInstructionAr: 'نقفل المسافة بين الراك والبلاط (نقص البلاط على المقاس أو نظبط القاعدة).',
    fixInstructionEn: 'Close the gap between rack and tiles (tile cut to size or base adjusted).',
  },
  {
    code: 'WALL_OPENING_NOT_SEALED',
    group: 'floor_rack',
    origin: 'snag_docs',
    titleEn: 'Wall/ceiling cable opening not sealed (الشنيشه)',
    titleAr: 'الشنيشة (فتحة الحيطة) مش مقفولة',
    descriptionEn: 'Cable penetration through a wall or ceiling is left open/broken instead of being closed and filled (fire foam) after installation.',
    descriptionAr: 'فتحة عدية الكابلات في الحيطة أو السقف (الشنيشة) متسابة مفتوحة أو مكسرة ومتقفلتش ومتملتش فوم بعد التركيب.',
    defaultSeverity: 'major',
    categories: ['power_path', 'earth_path', 'armoured_cables', 'uplink', 'duct', 'management'],
    visualCues: ['broken plaster around cables entering a wall', 'open hole around cable bundle at wall/ceiling', 'no foam / sealing around penetration'],
    confusableWith: ['FLOOR_OPENING_NOT_SEALED', 'RUBBER_GLAND_MISSING'],
    reviewerPhrasesAr: ['نقفل الشينشه', 'نقفل الشنيشه'],
    fixInstructionAr: 'نقفل الشنيشة ونملاها فوم ونشطب حواليها.',
    fixInstructionEn: 'Close the wall opening, fill it with fire foam and finish around it.',
  },
  {
    code: 'RACK_BASE_BOLTS_MISSING',
    group: 'floor_rack',
    origin: 'snag_docs',
    titleEn: 'Rack base leg bolts missing (8 per leg)',
    titleAr: 'مسامير رجل القاعدة ناقصة (8 مسامير)',
    descriptionEn: 'Each leg of the rack base must be fixed with 8 bolts; one or more bolt holes are empty.',
    descriptionAr: 'كل رجل من رجول قاعدة الراك لازم تتربط بـ 8 مسامير، وفيه خرم أو أكتر فاضي.',
    defaultSeverity: 'major',
    categories: ['rack_base'],
    visualCues: ['empty bolt holes on the vertical leg brackets', 'fewer bolts on one leg than on the others', 'floor anchor plate without anchor bolt'],
    confusableWith: ['RACK_BASE_NOT_LEVEL'],
    reviewerPhrasesAr: ['نحط 8 مسامير في كل رجل من القاعده'],
    fixInstructionAr: 'نركب 8 مسامير في كل رجل من القاعدة ونربطها كويس.',
    fixInstructionEn: 'Fit and tighten all 8 bolts on every base leg.',
  },
  {
    code: 'RACK_BASE_NOT_LEVEL',
    group: 'floor_rack',
    origin: 'sid_checklist',
    titleEn: 'Rack base not level / not at tile level',
    titleAr: 'قاعدة الراك مش مظبوطة على الميزان أو مستوى البلاط',
    descriptionEn: 'The metal base is not level (spirit level bubble off-centre) or its top is not flush with the raised-floor tiles.',
    descriptionAr: 'القاعدة الحديد مش مظبوطة على الميزان (الفقاعة مش في النص) أو سطحها مش في مستوى البلاط.',
    defaultSeverity: 'major',
    categories: ['rack_base'],
    visualCues: ['spirit level bubble off-centre', 'base frame top higher or lower than surrounding tiles', 'frame visibly twisted'],
    confusableWith: ['RACK_BASE_BOLTS_MISSING', 'RACK_FLOOR_GAP'],
    reviewerPhrasesAr: [],
    fixInstructionAr: 'نظبط القاعدة على الميزان وعلى مستوى البلاط ونصورها والميزان عليها.',
    fixInstructionEn: 'Level the base flush with the tiles and photograph it with the spirit level on top.',
  },
  {
    code: 'RACK_MISALIGNED',
    group: 'floor_rack',
    origin: 'sid_checklist',
    titleEn: 'Rack not aligned with row / floor tile edge',
    titleAr: 'الراك مش على استقامة الصف أو حرف البلاط',
    descriptionEn: 'Rack front is not aligned with adjacent racks or with the floor-tile edge.',
    descriptionAr: 'وش الراك مش على استقامة الراكات اللي جنبه أو مع حرف البلاط.',
    defaultSeverity: 'minor',
    categories: ['rack'],
    visualCues: ['rack front set back or forward relative to neighbours', 'rack rotated relative to the tile grid'],
    confusableWith: ['RACK_FLOOR_GAP'],
    reviewerPhrasesAr: [],
    fixInstructionAr: 'نظبط الراك على استقامة الصف وحرف البلاط.',
    fixInstructionEn: 'Align the rack with the row and the tile edge.',
  },

  // ───────────────────────────── labels ─────────────────────────────
  {
    code: 'HOSTNAME_LABEL_MISSING',
    group: 'labels',
    origin: 'snag_docs',
    titleEn: 'Hostname label missing on router/rack',
    titleAr: 'الهوست نيم مش موجود',
    descriptionEn: 'The router (or rack/ODF it belongs to) has no hostname label (e.g. SITE-R21C-C-EG) in the agreed position.',
    descriptionAr: 'الراوتر (أو الراك/الاو دي اف) مفيش عليه ليبول الهوست نيم (زي SITE-R21C-C-EG) في المكان المتفق عليه.',
    defaultSeverity: 'major',
    categories: ['router', 'rack', 'odf_cross_connect', 'odf_tie', 'pdu', 'test_room'],
    visualCues: ['blank label area on router front/side panel', 'rack top without name strip', 'ODF front without its ODF name'],
    confusableWith: ['LABEL_MISSING'],
    reviewerPhrasesAr: ['الهوست نيم مش موجود'],
    fixInstructionAr: 'نطبع ليبول الهوست نيم بالفورمات المتفق عليه ونلزقه في مكانه.',
    fixInstructionEn: 'Print the hostname label in the agreed format and fix it in its position.',
  },
  {
    code: 'LABEL_MISSING',
    group: 'labels',
    origin: 'snag_docs',
    titleEn: 'Cable / port label missing',
    titleAr: 'الليبول مش موجود',
    descriptionEn: 'A patch cord, power/earth cable, uplink, PDU breaker or device has no label where one is required. Use HOSTNAME_LABEL_MISSING for the device name label.',
    descriptionAr: 'باتش أو كابل باور/أرضي أو أب لينك أو بريكر في الـ PDU أو جهاز من غير ليبول. ليبول اسم الجهاز ليه كود HOSTNAME_LABEL_MISSING.',
    defaultSeverity: 'major',
    categories: LABELLED,
    visualCues: ['cord ends without a flag label', 'power cable without label near termination', 'blank label slots on PDU breakers'],
    confusableWith: ['HOSTNAME_LABEL_MISSING', 'LABEL_INFO_INCOMPLETE'],
    reviewerPhrasesAr: ['نحط الليبول', 'عدم وجود ليبول'],
    fixInstructionAr: 'نحط ليبول على كل كابل أو باتش ناقص بالفورمات المتفق عليه (From / To).',
    fixInstructionEn: 'Add a label in the agreed From/To format to every unlabelled cable or cord.',
  },
  {
    code: 'LABEL_DAMAGED',
    group: 'labels',
    origin: 'snag_docs',
    titleEn: 'Label torn / damaged',
    titleAr: 'الليبول مقطوع',
    descriptionEn: 'A label exists but is torn, peeling, crumpled or partially missing.',
    descriptionAr: 'الليبول موجود بس مقطوع أو بيقشر أو متكرمش أو جزء منه ناقص.',
    defaultSeverity: 'minor',
    categories: LABELLED,
    visualCues: ['ripped edge on flag label', 'label peeling off the cable', 'half a label left'],
    confusableWith: ['LABEL_MISSING', 'LABEL_INFO_INCOMPLETE'],
    reviewerPhrasesAr: ['الليبول مقطوع'],
    fixInstructionAr: 'نغير الليبول المقطوع بليبول جديد.',
    fixInstructionEn: 'Replace the damaged label.',
  },
  {
    code: 'LABEL_MISPLACED',
    group: 'labels',
    origin: 'snag_docs',
    titleEn: 'Label in wrong position',
    titleAr: 'الليبول مش في مكانه',
    descriptionEn:
      'Label is fixed in the wrong place (e.g. hostname label not aligned on the screw line of the router lid, label hidden behind other cords, far from the termination).',
    descriptionAr: 'الليبول متلزق في مكان غلط (زي ليبول الهوست نيم مش على المسمار، أو مستخبي ورا البشات، أو بعيد عن طرف الكابل).',
    defaultSeverity: 'minor',
    categories: LABELLED,
    visualCues: ['hostname strip offset from the screw / reference line', 'labels bunched far from connectors', 'label facing away / hidden'],
    confusableWith: ['LABEL_MISSING'],
    reviewerPhrasesAr: ['وضح الليبول علي مسمار'],
    fixInstructionAr: 'نشيل الليبول ونلزقه في المكان الصح (على المسمار / جنب الطرف).',
    fixInstructionEn: 'Re-fix the label in the correct position (on the screw line / next to the termination).',
  },
  {
    code: 'LABEL_INFO_INCOMPLETE',
    group: 'labels',
    origin: 'sid_checklist',
    titleEn: 'Label content incomplete / not in agreed format',
    titleAr: 'بيانات الليبول ناقصة أو مش بالفورمات',
    descriptionEn: 'Label is readable but lacks required info (From / To, port, circuit ID, power type/level) or is hand-written instead of printed.',
    descriptionAr: 'الليبول بيتقري بس ناقص بيانات (From / To، البورت، Circuit ID، نوع الباور) أو مكتوب بخط اليد مش مطبوع.',
    defaultSeverity: 'major',
    categories: LABELLED,
    visualCues: ['only one end written (From without To)', 'hand-written marker label', 'power label without feed/level info'],
    confusableWith: ['LABEL_DAMAGED', 'LABEL_MISSING'],
    reviewerPhrasesAr: [],
    fixInstructionAr: 'نطبع ليبول جديد فيه From و To والبورت بالفورمات المتفق عليه.',
    fixInstructionEn: 'Print a new label with From, To and port in the agreed format.',
  },

  // ───────────────────────────── power / earth ─────────────────────────────
  {
    code: 'POWER_PLUG_EXPOSED',
    group: 'power',
    origin: 'snag_docs',
    titleEn: 'Loose power plug / cord visible (الفيشه)',
    titleAr: 'الفيشة باينة',
    descriptionEn: 'An unused or loose AC power cord/plug (e.g. rack fan cord) is left hanging or coiled visibly in the rack instead of being hidden/dressed.',
    descriptionAr: 'فيشة أو سلك باور (زي فيشة مراوح الراك) متسابة مدلدلة أو ملفوفة وباينة في الراك بدل ما تتخبى وتتسستم.',
    defaultSeverity: 'minor',
    categories: ['rack', 'pdu', 'power_system', 'router'],
    visualCues: ['black AC plug hanging at top of rack', 'coiled power cord tied on a panel', 'loose plug resting on equipment'],
    confusableWith: ['POWER_CABLE_ROUTING_UNTIDY'],
    reviewerPhrasesAr: ['اخفاء الفيشه', 'نخفي الفيشه'],
    fixInstructionAr: 'نخفي الفيشة ونلم السلك ونربطه ورا البانل.',
    fixInstructionEn: 'Hide the plug and dress the cord out of sight behind the panel.',
  },
  {
    code: 'PDU_SCREW_MISSING',
    group: 'power',
    origin: 'snag_docs',
    titleEn: 'PDU fixing screw missing',
    titleAr: 'مسمار الـ PDU ناقص',
    descriptionEn: 'One or more rack-mount screws/cage nuts of the PDU (or its cover) are missing.',
    descriptionAr: 'مسمار أو أكتر من مسامير تثبيت الـ PDU (أو الغطا بتاعه) في الراك ناقص.',
    defaultSeverity: 'major',
    categories: ['pdu', 'rack', 'power_system'],
    visualCues: ['empty mounting hole on PDU ear', 'fewer screws on one side than the other', 'PDU cover not screwed'],
    confusableWith: [],
    reviewerPhrasesAr: ['مسمار  بي دي يو'],
    fixInstructionAr: 'نركب كل مسامير الـ PDU ونربطها.',
    fixInstructionEn: 'Fit and tighten all PDU mounting screws.',
  },
  {
    code: 'POWER_CABLE_DAMAGED',
    group: 'power',
    origin: 'snag_docs',
    titleEn: 'Power/earth cable insulation scratched or damaged',
    titleAr: 'خدوش في كابل الباور',
    descriptionEn: 'Insulation of a power or earth cable (or its lug sleeve) is scratched, cut or exposes conductor.',
    descriptionAr: 'عزل كابل الباور أو الأرضي (أو جلبة الكوس) فيه خدوش أو قطع أو النحاس باين.',
    defaultSeverity: 'critical',
    categories: POWER,
    visualCues: ['scuffed / cut insulation', 'copper visible near a lug', 'tape wrapped over damage'],
    confusableWith: [],
    reviewerPhrasesAr: ['يوجد خدوش في كابل الباور'],
    fixInstructionAr: 'نغير الكابل المخدوش أو الجزء التالف (مش بنلفه بلزق).',
    fixInstructionEn: 'Replace the damaged cable or section (taping over is not accepted).',
  },
  {
    code: 'BUSBAR_WRONG_DRILLING',
    group: 'power',
    origin: 'snag_docs',
    titleEn: 'Wrong / extra drilling on busbar',
    titleAr: 'تخريم في مكان غلط في البارة',
    descriptionEn: 'Holes drilled in the wrong place on a power or earth busbar (extra unused holes, damaged paint/plating around holes).',
    descriptionAr: 'خروم متخرمة في مكان غلط في بارة الباور أو الأرضي (خروم زيادة مش مستخدمة أو دهان باظ حواليها).',
    defaultSeverity: 'major',
    categories: ['power_path', 'earth_path', 'power_system', 'pdu'],
    visualCues: ['empty fresh drill hole with bare metal ring', 'hole between existing terminals', 'swarf / damaged coating around hole'],
    confusableWith: [],
    reviewerPhrasesAr: ['في تخريم في مكان غير صحيح في الباره'],
    fixInstructionAr: 'نرجع للاستشاري: يا نغير البارة يا نعالج الخرم حسب التعليمات، ونخرم بعد كده في الأماكن المعتمدة بس.',
    fixInstructionEn: 'Escalate: replace the bar or treat the hole as instructed; drill only at approved positions.',
  },
  {
    code: 'POWER_CABLE_ROUTING_UNTIDY',
    group: 'power',
    origin: 'sid_checklist',
    titleEn: 'Power/earth cable dressing untidy or mixed with data',
    titleAr: 'سستمة كابلات الباور مش مظبوطة',
    descriptionEn:
      'Power or earth cables not bundled with tie-wraps, not on their own side of the tray/ladder, or run together with fiber/UTP (SID requires ~30 cm separation).',
    descriptionAr: 'كابلات الباور أو الأرضي مش متربطة بتاي راب كويس، أو مش في الجنب بتاعها من التراي، أو ماشية مع الفايبر أو الـ UTP (المطلوب حوالي 30 سم فصل).',
    defaultSeverity: 'major',
    categories: POWER,
    visualCues: ['power cables crossing over each other on the ladder', 'missing or irregular tie-wraps', 'power and data in the same bundle/tray side'],
    confusableWith: ['POWER_PLUG_EXPOSED', 'MANAGEMENT_CABLE_UNTIDY'],
    reviewerPhrasesAr: [],
    fixInstructionAr: 'نعيد سستمة كابلات الباور بتاي راب على مسافات ثابتة وفي جنب لوحدها بعيد عن الداتا.',
    fixInstructionEn: 'Re-dress power cables with evenly spaced tie-wraps, on their own side away from data cables.',
  },

  // ───────────────────────────── other cabling ─────────────────────────────
  {
    code: 'MANAGEMENT_CABLE_UNTIDY',
    group: 'cabling',
    origin: 'snag_docs',
    titleEn: 'Management (UTP) cable routing untidy',
    titleAr: 'المانجمنت مش مظبوط',
    descriptionEn: 'The management/UTP cable is loose, not following the tray/organiser, hanging, or crossing the fiber bundle.',
    descriptionAr: 'كابل المانجمنت (UTP) سايب أو مش ماشي في التراي أو المنظم أو مدلدل أو معدي على البشات.',
    defaultSeverity: 'major',
    categories: ['management', 'router', 'rack', 'patch_cords'],
    visualCues: ['single grey/blue UTP cable running outside the organiser', 'UTP draped over fiber bundle', 'UTP loose between racks without tie'],
    confusableWith: ['PATCH_CORD_ROUTING_UNTIDY', 'POWER_CABLE_ROUTING_UNTIDY'],
    reviewerPhrasesAr: ['نظبط المانجمنيت', 'نظبط المانجمنت', 'نعدل المانجمنت', 'المانجمنت نظبطه', 'نظبط المانجممنت'],
    fixInstructionAr: 'نمشي كابل المانجمنت في مساره على التراي والمنظم ونربطه بعيد عن البشات.',
    fixInstructionEn: 'Route the management cable along the tray/organiser and tie it away from the fiber.',
  },
  {
    code: 'ARMOURED_CABLE_ROUTING_UNTIDY',
    group: 'cabling',
    origin: 'snag_docs',
    titleEn: 'Armoured fibre cable routing untidy',
    titleAr: 'سستمة الارمود مش مظبوطة',
    descriptionEn: 'Armoured fibre cable is not dressed neatly along its path (loose, crossing, not tied, slack not organised on the ladder).',
    descriptionAr: 'كابل الارمود مش متسستم كويس في مساره (سايب أو معدي على غيره أو مش متربط أو الاسبير بتاعه مش منظم على السلم).',
    defaultSeverity: 'major',
    categories: ['armoured_cables', 'odf_tie', 'test_room', 'duct'],
    visualCues: ['armoured cable snaking loosely in the tray', 'cable outside the duct/tray', 'armoured slack coil hanging unsecured'],
    confusableWith: ['FIBER_BEND_RADIUS_TOO_TIGHT'],
    reviewerPhrasesAr: ['نظبط سستمه الارمود', 'نظبط الارمود'],
    fixInstructionAr: 'نسستم الارمود في مساره ونربطه، ونلم الاسبير (2 متر) بشكل منظم.',
    fixInstructionEn: 'Dress and tie the armoured cable along its path; coil the 2 m spare neatly.',
  },

  // ───────────────────────────── documentation ─────────────────────────────
  {
    code: 'ODF_SHEET_MISSING_OR_UNREADABLE',
    group: 'documentation',
    origin: 'sid_checklist',
    titleEn: 'ODF port utilization sheet missing / unreadable',
    titleAr: 'شيت الاو دي اف مش موجود أو مش مقروء',
    descriptionEn: 'The printed port utilization sheet is not posted in a sleeve on the rack door, or it is unreadable/incomplete.',
    descriptionAr: 'شيت توزيع بورتات الاو دي اف مش متعلق في جراب على باب الراك، أو مش مقروء أو ناقص.',
    defaultSeverity: 'major',
    categories: ['odf_sheet', 'rack'],
    visualCues: ['rack door without the plastic sleeve and sheet', 'sheet hand-written or with empty columns', 'sheet torn / wet / faded'],
    confusableWith: ['PHOTO_BLURRY'],
    reviewerPhrasesAr: [],
    fixInstructionAr: 'نطبع شيت الاو دي اف المحدث ونعلقه في جراب على باب الراك.',
    fixInstructionEn: 'Print the up-to-date ODF sheet and post it in a sleeve on the rack door.',
  },

  // ───────────────────────────── catch-all ─────────────────────────────
  {
    code: 'OTHER_SNAG',
    group: 'other',
    origin: 'catch_all',
    titleEn: 'Other issue (not in taxonomy)',
    titleAr: 'ملاحظة تانية مش في القائمة',
    descriptionEn: 'A real installation defect that no other code describes. Explain it fully in reasonEn/reasonAr; these are reviewed to extend the taxonomy.',
    descriptionAr: 'عيب تركيب حقيقي مفيش كود يوصفه. لازم نشرح السبب كامل؛ الملاحظات دي بتتراجع عشان نضيف أكواد جديدة.',
    defaultSeverity: 'minor',
    categories: ALL,
    visualCues: ['any clear workmanship defect not covered by a specific code'],
    confusableWith: [],
    reviewerPhrasesAr: [],
    fixInstructionAr: 'حسب الملاحظة؛ المراجع هيحدد الإصلاح.',
    fixInstructionEn: 'Depends on the remark; the reviewer will specify the fix.',
  },
];

export const SNAG_CODES: readonly string[] = SNAG_TAXONOMY.map((s) => s.code);

const byCode = new Map(SNAG_TAXONOMY.map((s) => [s.code, s] as const));

export function getSnag(code: string): SnagDefinition | undefined {
  return byCode.get(code);
}

/** Codes applicable to a category, in taxonomy order (stable). */
export function snagsForCategory(category: PhotoCategory): SnagDefinition[] {
  return SNAG_TAXONOMY.filter((s) => s.categories.includes(category));
}

/**
 * Map a free-text reviewer remark (Arabic) to candidate codes by matching the
 * verbatim phrases. Whitespace and common variant letters are normalised.
 * Used by the snag-seed ingestion to pre-label historical remarks.
 */
export function matchReviewerRemark(remarkAr: string): string[] {
  const needle = normalizeArabic(remarkAr);
  if (needle.length < 3) return [];
  const hits: string[] = [];
  for (const s of SNAG_TAXONOMY) {
    const matched = s.reviewerPhrasesAr.some((p) => {
      const hay = normalizeArabic(p);
      // remark contains a known phrase, or remark is a substantial fragment of one
      return hay.length > 0 && (needle.includes(hay) || (needle.length >= 6 && hay.includes(needle)));
    });
    if (matched) hits.push(s.code);
  }
  // A fallback code is dropped when a more specific code of the same family also matched.
  return hits.filter((code) => {
    if (!FALLBACK_CODES.has(code)) return true;
    const specific = getSnag(code)?.confusableWith ?? [];
    return !hits.some((h) => specific.includes(h));
  });
}

/** Generic "untidy" codes used only when no specific code of the family applies. */
export const FALLBACK_CODES: ReadonlySet<string> = new Set(['PATCH_CORD_ROUTING_UNTIDY', 'OTHER_SNAG']);

export function normalizeArabic(text: string): string {
  return text
    .replace(/^[\s\d\-_—–.]+/, '') // leading numbering like "1-" / "2_"
    .replace(/[ً-ْـ]/g, '') // diacritics, tatweel
    .replace(/[أإآ]/g, 'ا')
    .replace(/ى/g, 'ي')
    .replace(/ة/g, 'ه')
    .replace(/[^؀-ۿa-zA-Z0-9]+/g, ' ')
    .trim();
}
