import { AlignmentType, BorderStyle, Paragraph, TextRun } from 'docx';
import type { ReportData } from '../data.js';
import { dataTable, para, run, THEME, type Block } from '../docx/primitives.js';
import { SECTIONS } from './titles.js';

export const formatDateTime = (iso: string): string => {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : `${d.toISOString().slice(0, 10)} ${d.toISOString().slice(11, 16)} UTC`;
};

/** Cover page (SID title page: document title, site, project) plus report identity. No logos. */
export function buildCover(data: ReportData): Block[] {
  const title = new Paragraph({
    spacing: { before: 2400, after: 120 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 24, color: '0070C0', space: 6 } },
    children: [new TextRun({ text: 'Site Information Document', bold: true, size: 44, color: THEME.titleColor, font: THEME.font })],
  });
  const siteName = data.siteData.siteName ?? data.site.name;
  const blocks: Block[] = [
    title,
    new Paragraph({ spacing: { before: 600, after: 120 }, alignment: AlignmentType.CENTER, children: [run(siteName, { bold: true, size: 56, color: THEME.accent })] }),
    para(`${data.project.name} Project`, { align: AlignmentType.CENTER, bold: true, size: 36, color: THEME.accent }),
    para(data.siteData.hostname ?? '', { align: AlignmentType.CENTER, size: 28, color: THEME.muted, spacingAfter: 600 }),
  ];
  if (data.meta.draft) {
    blocks.push(para('DRAFT – not for acceptance', { align: AlignmentType.CENTER, bold: true, size: 32, color: THEME.fail, spacingAfter: 400 }));
  }
  blocks.push(
    dataTable(
      [{ header: 'Report', weight: 1 }, { header: '', weight: 2 }],
      [
        ['Acceptance report version', `v${data.meta.version}${data.meta.draft ? ' (draft)' : ''}`],
        ['Generated at', formatDateTime(data.meta.generatedAt)],
        ['Generated by', `${data.meta.generatedBy.name} (${data.meta.generatedBy.role})`],
        ['Site code', data.site.code],
        ['Client', data.project.clientName ?? '—'],
      ],
      { width: 6000, size: 20 },
    ),
  );
  return blocks;
}

/** "Content:" page listing the 12 sections (numbered like the SID). */
export function buildContents(): Block[] {
  return [
    new Paragraph({ pageBreakBefore: true, spacing: { after: 240 }, children: [new TextRun({ text: 'Content:', bold: true, size: 32, color: '44546A', font: THEME.font })] }),
    ...SECTIONS.map((s, i) => para(`${i + 1}.  ${s.contents}`, { size: 28, spacingAfter: 80 })),
  ];
}
