import { HeadingLevel, Paragraph, TextRun } from 'docx';
import type { ReportData } from '../data.js';
import { dataTable, note, para, subHeading, THEME, type Block } from '../docx/primitives.js';
import { formatDateTime } from './front.js';

/** Appendix after the 12 SID sections: report metadata, AI statistics, warnings and sign-off. */
export function buildReportInfo(data: ReportData): Block[] {
  const { meta, ai } = data;
  const blocks: Block[] = [
    new Paragraph({ heading: HeadingLevel.HEADING_1, pageBreakBefore: true, children: [new TextRun('Report information and sign-off')] }),
    dataTable(
      [{ header: 'Field', weight: 2 }, { header: 'Value', weight: 5 }],
      [
        ['Report version', `v${meta.version}`],
        ['Status', meta.draft ? { text: 'DRAFT – generated with open items, not valid for acceptance', bold: true, color: THEME.fail } : 'FINAL'],
        ['Generated at', formatDateTime(meta.generatedAt)],
        ['Generated by', `${meta.generatedBy.name} (${meta.generatedBy.role})`],
        ['Report id', meta.reportId ?? '—'],
        ['Approved photos in gallery', String(data.gallery.length)],
      ],
    ),
    subHeading('AI inspection'),
  ];
  if (ai.models.length) {
    blocks.push(
      dataTable(
        [{ header: 'Provider', weight: 2 }, { header: 'Model', weight: 3 }, { header: 'Prompt version', weight: 3 }, { header: 'Analyses', weight: 1, align: 'center' }],
        ai.models.map((m) => [m.provider, m.model, m.promptVersion, m.analyses]),
      ),
    );
  } else {
    blocks.push(note('No AI analyses recorded for this site.'));
  }
  const agreement = ai.agreementRate === null ? 'n/a' : `${Math.round(ai.agreementRate * 1000) / 10}%`;
  blocks.push(para(`Human reviews: ${ai.reviews}. AI/human verdict agreement: ${agreement}. Every photo in this report was approved by a human reviewer.`, { size: 18 }));

  blocks.push(subHeading('Data quality warnings'));
  if (data.warnings.length) for (const w of data.warnings) blocks.push(para(`• ${w}`, { size: 16, spacingAfter: 40 }));
  else blocks.push(note('None.'));

  blocks.push(subHeading('Sign-off'));
  const reviewers = data.reviewers.length ? data.reviewers : [{ name: '', role: 'reviewer' }];
  blocks.push(
    dataTable(
      [{ header: 'Role', weight: 2 }, { header: 'Name', weight: 3 }, { header: 'Signature', weight: 3 }, { header: 'Date', weight: 2 }],
      [
        ['Contractor', data.siteData.contractor ?? '', '', ''],
        ...reviewers.map((r) => [`Reviewer (${r.role})`, r.name, '', '']),
        [`Client acceptance${data.project.clientName ? ` – ${data.project.clientName}` : ''}`, '', '', ''],
      ],
      { size: 20 },
    ),
  );
  return blocks;
}
