import type { FewShotManifest } from './fewshot.js';

/**
 * Curated few-shot manifest (T3.5). GENERATED by `pnpm --filter @acceptance/ai fewshot:build` from
 * eval/fewshot-curation.ts - edit the picks there. Images are NOT in git (see fewshot.ts / README).
 */
export const FEW_SHOT_MANIFEST: FewShotManifest = {
  "version": "fs1-2026-10-03",
  "maxSide": 768,
  "examples": [
    {
      "id": "9b7fdc64118f031068860e52ccd4c9084d070e76bee6b0dc4af6c6a0f666615d",
      "category": "armoured_cables",
      "kind": "good",
      "codes": [],
      "explanation": "Armoured cable on the ladder; ordinary building dust on the old floor is not a snag.",
      "source": "NASR3...C(R21C)/NASR3...C(R21C)/photos/ARMOUD PATH/WhatsApp Image 2026-02-03 at 2.12.2.jpeg"
    },
    {
      "id": "4c4bcc4760e61b850c1e7a5aedcfd1f305e4c113144a4fa96b5d12c61ec2d5ea",
      "category": "armoured_cables",
      "kind": "good",
      "codes": [],
      "explanation": "Armoured cables dressed along the ladder and tied; this is the expected standard.",
      "source": "NASR3...C(R21C)/NASR3...C(R21C)/photos/ARMOUD PATH/WhatsApp Image 2026-02-03 at 2.12.18 PM.jpeg"
    },
    {
      "id": "89d4f30ee3b0a33f939758937c0f81bc6d7043ee7865dc1701c3ba54a67244a1",
      "category": "duct",
      "kind": "good",
      "codes": [],
      "explanation": "Closed duct with covers on; small gaps between cover sections and the open finger-type bend fittings are normal.",
      "source": "NCS-57C3/NCS-57C3/Duct/Duct With Cover NCS-57C3 (2).jpeg"
    },
    {
      "id": "e5d3eb460acf3afe045651f85bf577d9f382bb93d629ca5f9992286d28057f26",
      "category": "duct",
      "kind": "good",
      "codes": [],
      "explanation": "Duct run with covers fitted; nothing to remark.",
      "source": "9902/9902/Duct/Duct With Cover ASR9902  (5).jpeg"
    },
    {
      "id": "ce8d9783219ed112883e9ae9ec2593d8ce600d111b9301f974169dd63f12fc47",
      "category": "earth_path",
      "kind": "good",
      "codes": [],
      "explanation": "Earth cable tied along the under-floor ladder; pre-existing dirt under the raised floor is not a snag.",
      "source": "9906/9906/Power/Earth path/Earth Cables Pasth ASR9906 (3).jpeg"
    },
    {
      "id": "d17e654dfdcdfee7d72418719199314aaa54779826e672f656718656a087c810",
      "category": "earth_path",
      "kind": "good",
      "codes": [],
      "explanation": "Earth bar connection with labelled lugs; accepted.",
      "source": "NASR3...C(R21C)/NASR3...C(R21C)/photos/Earth Path/WhatsApp Image 2026-02-03 at 2.37.44 PM.jpeg"
    },
    {
      "id": "3d86a94aa4a87db83c9051355054f681650c70ab38a020adcd931e4765836ad8",
      "category": "management",
      "kind": "good",
      "codes": [],
      "explanation": "Management cable routed in the tray and tied; accepted.",
      "source": "9906/9906/Managment/Managment Path ASR9906 (1).jpeg"
    },
    {
      "id": "a4b86628be05551329031f3a0815d01ef0889523ec0412c744c9e1c88bee83a4",
      "category": "management",
      "kind": "good",
      "codes": [],
      "explanation": "Management cable path; accepted.",
      "source": "9902/9902/Managment/Managment Path ASR9902  (5).jpeg"
    },
    {
      "id": "0f63b9f9a3df6e6d7798fb59a591e0fb1e2f108b422a751540673d3fde6592f1",
      "category": "odf_cross_connect",
      "kind": "good",
      "codes": [],
      "explanation": "ODF with cords bundled in velcro, labels hanging on the cords, no spares inside; accepted.",
      "source": "NCS-57C3/NCS-57C3/ODF Cross Connect/ODF Cross Connect (4).jpeg"
    },
    {
      "id": "e4072b7de668d62aaf55f904bf7cedb4f324a4cc01c1e6ac8dd39f1023bb7b59",
      "category": "odf_cross_connect",
      "kind": "good",
      "codes": [],
      "explanation": "Close-up inside the ODF; labels and cords as expected; accepted.",
      "source": "NASR3...C(R21C)/NASR3...C(R21C)/photos/SW ROOM/ODFS/ODF(1)CC/WhatsApp Image 2026-02-03 at 11.41.50 AM.jpeg"
    },
    {
      "id": "28aa625d7370f72ded62906dbddbabb02e0ecb0a4efa8977ef62067d039a4803",
      "category": "odf_cross_connect_labels",
      "kind": "good",
      "codes": [],
      "explanation": "Printed cord labels read in a close-up, fingers may hold them; accepted.",
      "source": "9902/9902/ODF Cross Connect/Labels Cross Connect/Lables ODF Cross Connect  ASR9902 (2).jpeg"
    },
    {
      "id": "b468fe94b0ab6968f3b07bd651ba942dbfb8298d26b53681a25a25bd16f486d1",
      "category": "odf_cross_connect_labels",
      "kind": "good",
      "codes": [],
      "explanation": "Label close-up; short \"ODF-CC x(y,z)\" text is the agreed format, not incomplete.",
      "source": "9902/9902/ODF Cross Connect/Labels Cross Connect/Lables ODF Cross Connect  ASR9902 (20).jpeg"
    },
    {
      "id": "420e99ce87e3756aec7aa034ba42fd2d51e109ee89e71c021fb651d6cbaf4190",
      "category": "odf_sheet",
      "kind": "good",
      "codes": [],
      "explanation": "ODF port sheet in its plastic sleeve; partly cropped or glossy sheets are still accepted.",
      "source": "9902/9902/Sheet ODF/Sheet ODF ASR9902  (3).jpeg"
    },
    {
      "id": "676afab35e9b5c2663e9ccf08563ff9e6f6e31e152920c08cf0fb0fdaf03496a",
      "category": "odf_sheet",
      "kind": "good",
      "codes": [],
      "explanation": "ODF sheet posted on the door; accepted.",
      "source": "NASR3...C(R21C)/NASR3...C(R21C)/photos/SW ROOM/ODF SHEET/WhatsApp Image 2026-02-03 at 2.40.46 PM.jpeg"
    },
    {
      "id": "9441f5bbc72fcc66600cabb5e5c5614bb798d6ca8644767e59a66acf82c9a887",
      "category": "odf_tie",
      "kind": "good",
      "codes": [],
      "explanation": "Tie ODF with armoured cable entry and labelled cords; accepted.",
      "source": "NASR3...C(R21C)/NASR3...C(R21C)/photos/SW ROOM/ODFS/ODF(3)MMR/WhatsApp Image 2026-02-03 at 12.33.12 PM.jpeg"
    },
    {
      "id": "c9ba93688c14e8b366c6de26e210651b68154064656c2f07f32a5c9a6d18ae72",
      "category": "odf_tie",
      "kind": "good",
      "codes": [],
      "explanation": "Tie ODF close-up; accepted.",
      "source": "NASR3...C(R21C)/NASR3...C(R21C)/photos/SW ROOM/ODFS/ODF(3)MMR/WhatsApp Image 2026-02-03 at 12.32.46 PM.jpeg"
    },
    {
      "id": "522ebadde1711a0dd0a12f2fde4dd309f2e5de986358345dfd9e04e281994bf8",
      "category": "odf_tie_labels",
      "kind": "good",
      "codes": [],
      "explanation": "Tie ODF label close-up; the short printed label is the agreed format.",
      "source": "9902/9902/ODF Tie/Labels ODF Tie/Lables ODF Tie ASR9902 (11).jpeg"
    },
    {
      "id": "3050040a9eddea2e23b22abc251a325f0eacd152ca6bf0802144fe0ee34df0e6",
      "category": "odf_tie_labels",
      "kind": "good",
      "codes": [],
      "explanation": "Tie ODF labels; accepted.",
      "source": "NCS-57C3/NCS-57C3/ODF Tie/Labels ODF Tie/ODF Tie Lables  (1).jpeg"
    },
    {
      "id": "aa0b1214f1639979fd5bc74a92aa9a6dec2fa639ae420ec71543e8b64a0c8ce1",
      "category": "patch_cords",
      "kind": "good",
      "codes": [],
      "explanation": "Patch cords in the overhead tray, bundled with velcro; accepted.",
      "source": "9902/9902/Patch Cords/Patch Cord ASR9902  (4).jpeg"
    },
    {
      "id": "5673ccfe6f6902fbe3b544fce168259e3c8841ebf77dac9ae5a19fa10b1fa31b",
      "category": "patch_cords",
      "kind": "good",
      "codes": [],
      "explanation": "Patch cord bundles splitting towards several racks is the design, not multiple paths; accepted.",
      "source": "9906/9906/Patch Cords/Patch Cord Saystam ASR9906  (16).jpeg"
    },
    {
      "id": "44aec038b6e9aa57e589776e7cdaf7193c47d79dbba516a5b349167d45ebc1c9",
      "category": "pdu",
      "kind": "good",
      "codes": [],
      "explanation": "PDU with breakers and labelled feed cables; blank labels on unused breakers are fine.",
      "source": "9906/9906/Power/PDU/PDU With Cover (1).jpeg"
    },
    {
      "id": "e7e24f92ca6d7aab08613cbbaba39499ff52f783c2ac4a0fb4d3af1616ca5c6a",
      "category": "pdu",
      "kind": "good",
      "codes": [],
      "explanation": "PDU without cover; accepted.",
      "source": "9906/9906/Power/PDU/PDU Without Cover (3).jpeg"
    },
    {
      "id": "32a754762ef1d98304fe03720d862095eddbfbb873a6286085f1702928f48200",
      "category": "power_labels",
      "kind": "good",
      "codes": [],
      "explanation": "Printed wrap-around power labels; accepted.",
      "source": "9906/9906/Power/Lables/Power Cables Lables ASR9906 (6).jpeg"
    },
    {
      "id": "d58c74db82427221c8c103ff495db3fca2bb26860786d35811cd22def936358c",
      "category": "power_labels",
      "kind": "good",
      "codes": [],
      "explanation": "Power cable labels; accepted.",
      "source": "NCS-57C3/NCS-57C3/Power/Lables/Power Cables Labels NCS-57C3  (10).jpeg"
    },
    {
      "id": "2d0c112f6e2124a9c027627c2fde2650b20521a0a678fb7becbf098252fbf077",
      "category": "power_path",
      "kind": "good",
      "codes": [],
      "explanation": "Power cables on the under-floor ladder; old floor dirt is not a snag.",
      "source": "9902/9902/Power/Power Path/Power Path ASR 9902 (22).jpeg"
    },
    {
      "id": "b9a61f461253bd2b2b54c98b2899f9a2cd0ab32189e745c7116874879137e8c6",
      "category": "power_path",
      "kind": "good",
      "codes": [],
      "explanation": "Power path; accepted.",
      "source": "9906/9906/Power/Power Path/Power Cables Path ASR9906 (8).jpeg"
    },
    {
      "id": "3f286417d0c217a881a959026d6f1d121320d1e06d478cd59f341d3e4050e557",
      "category": "power_system",
      "kind": "good",
      "codes": [],
      "explanation": "Power cables dressed and tied; accepted.",
      "source": "9902/9902/Power/saystem/Power Cables Saystem (10).jpeg"
    },
    {
      "id": "f0aa0f7dad9d4b7a01e8eda08259166c80b4c67a665c774bed590963a2d3b4a3",
      "category": "power_system",
      "kind": "good",
      "codes": [],
      "explanation": "Power cable dressing; accepted.",
      "source": "9906/9906/Power/saystem/Power Cables Saystem ASR9906 (4).jpeg"
    },
    {
      "id": "86b16c5902fb231e80b4adca63ccd25b527ae50ee34dc64a206c41117656807e",
      "category": "rack",
      "kind": "good",
      "codes": [],
      "explanation": "Rack with doors open to show the inside; open doors in an inside shot are normal.",
      "source": "9902/9902/Rack/Rack ASR9902 (3).jpeg"
    },
    {
      "id": "891594ce2186fe1a5452a49e9acdc3b5956057c743210af74e8e0a14698662bf",
      "category": "rack",
      "kind": "good",
      "codes": [],
      "explanation": "Rack overview; accepted.",
      "source": "NASR3...C(R21C)/NASR3...C(R21C)/photos/SW ROOM/RACKS/WhatsApp Image 2026-02-03 at 11.06.07 AM.jpeg"
    },
    {
      "id": "2e599812012f1d41d6924d5bcc8a43f526adbad51d2b72b50ab6995926c52397",
      "category": "rack_base",
      "kind": "good",
      "codes": [],
      "explanation": "Rack base with spirit level and bolts; accepted.",
      "source": "9902/9902/Rack Base/Rack Base ASR9902 (1).jpeg"
    },
    {
      "id": "ca412036bd790174931b531e5d1ea1c6a747ed05e8ae3b75ced03770ee95db66",
      "category": "rack_base",
      "kind": "good",
      "codes": [],
      "explanation": "Rack base; accepted.",
      "source": "9906/9906/Rack Base/Rack Base ASR9906  (4).jpeg"
    },
    {
      "id": "9535e2c05fbf7ecddddfa320d1550a35ada52c3f3dbea1019973e090b8751931",
      "category": "router",
      "kind": "good",
      "codes": [],
      "explanation": "Router front with labelled cords; accepted.",
      "source": "NCS-57C3/NCS-57C3/Router/Router NCS-57C3 (1).jpeg"
    },
    {
      "id": "71f1683dcecca4373c54d5e5f4336149f9c5c591fc75fd9b09e981ea605bce05",
      "category": "router",
      "kind": "good",
      "codes": [],
      "explanation": "Router close-up; accepted.",
      "source": "NASR3...C(R21C)/NASR3...C(R21C)/photos/SW ROOM/Router/WhatsApp Image 2026-02-03 at 11.35.44 AM.jpeg"
    },
    {
      "id": "4a7e155580476a3b7258706b2f062bd25af2e0cddd7c065e19de373cf2d8b803",
      "category": "test_room",
      "kind": "good",
      "codes": [],
      "explanation": "ODF tie in the test room; accepted.",
      "source": "9906/9906/Test Room/ODF Tie In Test Room ASR9906 (2).jpeg"
    },
    {
      "id": "d0750291660449136917353a69303cd3ba9826a612471701ebf8ef123ed50b82",
      "category": "test_room",
      "kind": "good",
      "codes": [],
      "explanation": "Rack in the test room; accepted.",
      "source": "NCS-57C3/NCS-57C3/Test Room/Rack In Test Room NCS-57C3 (3).jpeg"
    },
    {
      "id": "00641b47c39af34e4a5ebad11bc70d29691fcb83b5428997d2757f94846e8665",
      "category": "uplink",
      "kind": "good",
      "codes": [],
      "explanation": "Uplink cords in the tray following the patch cord bundle; accepted.",
      "source": "9906/9906/uplink/Uplink Path ASR9906 (5).jpeg"
    },
    {
      "id": "94939ab91077ca734f56b5b88ecc1e5be673e505a9662af80601d92cb2ed38c6",
      "category": "uplink",
      "kind": "good",
      "codes": [],
      "explanation": "Uplink path; accepted.",
      "source": "9902/9902/uplink/uplink (6).jpeg"
    },
    {
      "id": "1d6ab7f47ad66e3782f9a63fc39d7a934ed4bccd4f0010e77e68d21bcf65e7b2",
      "category": "uplink_labels",
      "kind": "good",
      "codes": [],
      "explanation": "Two-line uplink label (local and remote hostname/port); accepted.",
      "source": "NCS-57C3/NCS-57C3/uplink/Uplink Lables/Uplink Lables NCS-57C3 (5).jpeg"
    },
    {
      "id": "c6c8f9b18cc41be333110cbbae82672980a041d026e01edd8f94b6cdfc825049",
      "category": "uplink_labels",
      "kind": "good",
      "codes": [],
      "explanation": "Uplink label close-up; accepted.",
      "source": "NCS-57C3/NCS-57C3/uplink/Uplink Lables/Uplink Lables NCS-57C3 (1).jpeg"
    },
    {
      "id": "902ddc597289fdc75ff81b4ad4615ae93c00ba43d0701ecd62d0c7beefbd941f",
      "category": "odf_cross_connect",
      "kind": "snag",
      "codes": [
        "DUST_CAP_MISSING",
        "SPARE_LEFT_IN_ODF"
      ],
      "note": "نشيل الاسيبر من الاو دي اف / الكابلر بدون غطاء",
      "explanation": "The reviewers rejected it for: Dust cap missing on unused coupler/port; Spare cords/items left inside ODF.",
      "source": "snags/po18/27.jpeg"
    },
    {
      "id": "5816297cd164dc45b229f98b2e9cc89a08d70bb57ee9dec1e20528b0f427c358",
      "category": "odf_tie",
      "kind": "snag",
      "codes": [
        "DUST_CAP_MISSING",
        "PATCH_CORD_ROUTING_UNTIDY"
      ],
      "note": "نغطي الكابلر ونعدل السستمه",
      "explanation": "The reviewers rejected it for: Dust cap missing on unused coupler/port; Patch cord dressing untidy (السستمه) — fallback.",
      "source": "snags/po17/26.jpeg"
    },
    {
      "id": "a60cb87cd34094503623220549aeffe9fac3fbb95c8a0cf669a8605d8a9742e6",
      "category": "patch_cords",
      "kind": "snag",
      "codes": [
        "PATCH_CORD_NOT_BUNDLED"
      ],
      "note": "نظبط السستمه",
      "explanation": "The reviewers rejected it for: Patch cords not bundled with velcro (اسكوتش).",
      "source": "snags/po18/37.jpeg"
    },
    {
      "id": "05eafd82004b5265b5360e6a28a6617709b54bb2824fddf505e16fea2734e1ff",
      "category": "duct",
      "kind": "snag",
      "codes": [
        "DUCT_COVER_OPEN"
      ],
      "note": "نقفل الداكت من النزله",
      "explanation": "The reviewers rejected it for: Duct cover open / not closed at drop.",
      "source": "snags/po17/02.jpeg"
    },
    {
      "id": "629710671cbee11b2f256a3df5d1e029ba468b97e56c47c17aee98538e78c9f0",
      "category": "management",
      "kind": "snag",
      "codes": [
        "MANAGEMENT_CABLE_UNTIDY"
      ],
      "note": "نظبط المانجمنيت",
      "explanation": "The reviewers rejected it for: Management (UTP) cable routing untidy.",
      "source": "snags/po17/28.jpeg"
    },
    {
      "id": "c03b48e5ab4dead05e014792f9ae3f548d5daa05bcc8a2e86c8e1b286517c74b",
      "category": "rack",
      "kind": "snag",
      "codes": [
        "PDU_SCREW_MISSING",
        "POWER_PLUG_EXPOSED",
        "RACK_DOOR_NOT_CLOSED"
      ],
      "note": "الباب مفتوح / نخفي الفيشه / مسمار بي دي يو",
      "explanation": "The reviewers rejected it for: PDU fixing screw missing; Loose power plug / cord visible (الفيشه); Rack door left open / not latched.",
      "source": "snags/po18/24.jpeg"
    },
    {
      "id": "0af7670f93d94bb3baf0a0ad6ae0c256b37cc04fab298032acadc1743e860b2c",
      "category": "armoured_cables",
      "kind": "snag",
      "codes": [
        "ARMOURED_CABLE_ROUTING_UNTIDY"
      ],
      "note": "نظبط سستمه الارمود",
      "explanation": "The reviewers rejected it for: Armoured fibre cable routing untidy.",
      "source": "snags/po18/30.jpeg"
    },
    {
      "id": "2204c2b3547881682fe776fd2d0b85af3ff0eef60ed5b428f8641f79f81abc44",
      "category": "rack_base",
      "kind": "snag",
      "codes": [
        "RACK_BASE_BOLTS_MISSING"
      ],
      "note": "نحط 8 مسامير في كل رجل من القاعده",
      "explanation": "The reviewers rejected it for: Rack base leg bolts missing (8 per leg).",
      "source": "snags/po17/13.jpeg"
    },
    {
      "id": "d86782c893098634b07b63cbbfff2a8b0e96faf8c036443d3126c0746cb9fa74",
      "category": "router",
      "kind": "snag",
      "codes": [
        "HOSTNAME_LABEL_MISSING"
      ],
      "note": "الهوست نيم مش موجود",
      "explanation": "The reviewers rejected it for: Hostname label missing on router/rack.",
      "source": "snags/po17/09.jpeg"
    }
  ]
};
