import type { FewShotManifest } from './fewshot.js';

/**
 * Curated few-shot manifest (T3.5). Generated by `pnpm --filter @acceptance/ai fewshot:build`; edit the
 * curation list in eval/fewshot-curation.ts, not this file. Images are NOT in git (see fewshot.ts).
 */
export const FEW_SHOT_MANIFEST: FewShotManifest = {
  version: 'fs0',
  maxSide: 768,
  examples: [],
};
